name: TG Music Bot

on:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04
    container: nikolaik/python-nodejs:python3.9-nodejs16

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name "${{ secrets.GH_NAME }}"
           git config --global user.email "${{ secrets.GH_MAIL }}"
           git config --global credential.helper store
           echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

       - name: Get repo
         continue-on-error: true
         run: |
           git clone https://github.com/AsmSafone/MusicPlayer bot

       - name: Get requirements
         continue-on-error: true
         run: |
           cd bot
           sudo apt install git curl python3-pip ffmpeg -y
           pip3 install -U pip
           curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
           sudo apt install -y nodejs
           sudo apt install build-essential
           sudo npm install pm2@latest -g
           pip3 install -U -r requirements.txt

       - name: Get config
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_NAME }}/${{ secrets.PR }} PR
           cp PR/.env bot/.env

       - name: Run the bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd bot
           python3 main.py

       - name: Loop
         continue-on-error: true
         run: |
              git clone https://github.com/${{ secrets.GH_REPO }} loop
              cd loop || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO }} HEAD:main
